# -*- coding: utf-8 -*-
"""Flowcharts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E2AGVPa1sMHP3dFYt8cRIDoOOZ7kB7hs

# Creating flowcharts using python
"""

pip install graphviz matplotlib

import graphviz
from graphviz import Digraph
import matplotlib.pyplot as plt
# Create a Digraph object
dot = Digraph(comment='Simple Flowchart')

# Add nodes to the flowchart
dot.node('A', 'Start')
dot.node('B', 'Process 1')
dot.node('C', 'Process 2')
dot.node('D', 'End')

# Add edges to connect the nodes
dot.edges(['AB', 'BC', 'CD'])

# Save the flowchart as a DOT file (optional)
dot.save('flowchart.dot')

# Render the flowchart as an image
dot.format = 'png'
dot.render('flowchart', view=False)

# Display the flowchart in the notebook
img = plt.imread('flowchart.png')
plt.figure(figsize=(8, 6))
plt.imshow(img)
plt.axis('off')
plt.show()

import graphviz
from graphviz import Digraph
import matplotlib.pyplot as plt

# Create a Digraph object
dot = Digraph(comment='Customized Flowchart')

# Add nodes with two lines of text
dot.node('A', 'Problem\nDefinition')
dot.node('B', 'Data\nGathering')
dot.node('C', 'Data\nProcessing')
dot.node('D', 'Model\nBuilding')
dot.node('E', 'Model\nDeployment')
dot.node('F', 'Metrics &\nDashboarding')
dot.node('G', 'Decision\nMaking')

# Add edges to connect the nodes
dot.edges(['AB', 'BC', 'CD', 'DE', 'EF', 'FG'])

# Save the flowchart as a DOT file (optional)
dot.save('custom_flowchart.dot')

# Render the flowchart as an image
dot.format = 'png'
dot.render('custom_flowchart', view=False)

# Display the flowchart in the notebook
img = plt.imread('custom_flowchart.png')
plt.figure(figsize=(10, 8))
plt.imshow(img)
plt.axis('off')
plt.show()